version: '3.6'
services:
    counter:
        build: .
        image: reg.istry.cz/dte03/counter
        ports:
            - 80:80
        depends_on:
            - redis
    redis:
        image: redis:alpine
