version: '3.6'
services:
    traefik:
        image: traefik
        command: --web --docker --docker.watch --entryPoints="Name:http Address::80"
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
              #- /dev/null:/traefik.toml

