version: '3.6'
services:
    counter:
        build: .
        image: reg.istry.cz/docker-training-example/counter
        depends_on:
            - redis
        labels:
            - traefik.frontend.rule=Host:localhost
    redis:
        image: redis:alpine
